### ISSUE TITLE
(Clutter) Importing without using

### ISSUE THREAD

**Issue by CharlesDLandau** [maeve70/intro-data-capstone-musclehub#2]
It's fine to import a library wholesale in many cases (so long as you use it,) but explicitly importing a callable from a library without using it in our code is not appropriate. Doing so can lead to readability and troubleshooting difficulties later on.

https://github.com/maeve70/intro-data-capstone-musclehub/blob/a884368cd992138a5c0c4c6e121bf441e5167d6e/MuscleHub_ABTest/musclehub%20copy.py#L255

You also import numpy twice, but comment out your numpy code. Clean up on aisle 3!
https://github.com/maeve70/intro-data-capstone-musclehub/blob/a884368cd992138a5c0c4c6e121bf441e5167d6e/MuscleHub_ABTest/musclehub%20copy.py#L407
https://github.com/maeve70/intro-data-capstone-musclehub/blob/a884368cd992138a5c0c4c6e121bf441e5167d6e/MuscleHub_ABTest/musclehub%20copy.py#L428

**Comment by maeve70** [comment]
Whoops! Good catch.
