### ISSUE TITLE
(Style) Comply with PEP-8!

### ISSUE THREAD

**Issue by CharlesDLandau** [maeve70/intro-data-capstone-musclehub#3]
You're far along enough now in terms of learning Python - you probably can't get away with PEP-8 violations much longer. There are lots of IDE extensions and Python libraries which can automatically check your code for compliance like flake8. Some IDEs like Spyder have it built-in, even.

One example, but you have a few: https://github.com/maeve70/intro-data-capstone-musclehub/blob/a884368cd992138a5c0c4c6e121bf441e5167d6e/MuscleHub_ABTest/musclehub%20copy.py#L160

**Comment by maeve70** [comment]
I'm not following with the issue is. I don't know what PEP-8 is. We didn't cover compliance in the course, but now I know. Thank you.
