### ISSUE TITLE
(Question) Did you write it this way?

### ISSUE THREAD

**Issue by CharlesDLandau** [maeve70/intro-data-capstone-musclehub#4]
This line is way less readable than "%matplotlib inline" -- did you write it this way, or I guess it got changed when the file was downloaded to a .py file?

https://github.com/maeve70/intro-data-capstone-musclehub/blob/a884368cd992138a5c0c4c6e121bf441e5167d6e/MuscleHub_ABTest/musclehub%20copy.py#L144

**Comment by maeve70** [comment]
Hi Charles,
That's so weird. No, I didn't write it that way. Haha. I used "%matplotlib inline"
