### ISSUE TITLE
(Presentation) Nice work!

### ISSUE THREAD

**Issue by CharlesDLandau** [maeve70/intro-data-capstone-musclehub#5]
Hey this presentation rocks! I only have a few quick notes.

Be concise! Infrequently a slide deck may be provided to a client as reading material, but even then the format suggests a high proportion of visual content to text. Some of your slides are all text, and you go into great detail which might be better moved to the notes section.

You can just say "we grouped x by y" I don't know if I would call it a "groupby method."

Data tables may not be the best format for a slide deck, but if you use them make sure to format them all consistently. Unless there is a compelling reason, rounding is appropriate instead of including many decimal places.

Proofread thoroughly!

**Comment by maeve70** [comment]
Thank you!
